name: My World

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildjob1:
    runs-on: ubuntu-latest
    steps:
    - name: buildstep1_1
      uses: actions/checkout@v4
    - name: buildstep1_2
      uses: actions/checkout@v4

  buildjob2:
    runs-on: macos-latest
    steps:
    - name: buildstep2_1
      uses: actions/checkout@v5

  buildjob3:
    runs-on: windows-latest
    steps: 
    - name: buildstep3_1
      run: echo "Hello Satheesh!!!"
